In [2]:
import numpy as np

In [3]:
def sigmoid(x, deriv=False):
    val = None
    if not deriv:
        val = 1.0/(1.0+np.exp(-x))
    else:
        val = np.exp(-x)/((np.exp(-x)+1)**2)
    return val

In [4]:
def MSE(y, target, deriv=False):
    n = y.shape[0]
    val = None
    if not deriv:
        val = np.sum((target-y)**2)/n
    else:
        val = -2.0*(target-y)/n
    return val

In [5]:
def crossEntropyLoss(y, target, deriv=False):
    n = y.shape[0]
    val = None
    if not deriv:
        val = -1.0*np.sum(target*np.log(y)+(1.0-target)*np.log(1.0-target))/n
    else:
        val = -(target/output) + ((1-target)/(1-output))
    return val

In [6]:
n_inputs = 20
n_hidden = 100
n_output = 10

lr = 0.01

In [7]:
target = np.random.randn(10)
target

array([-0.29769533, -0.21971084, -0.61309517, -0.05324452,  0.80514719,
       -0.96867515, -0.77814242, -0.19863168, -0.34148069,  0.04386213])

In [8]:
W1 = np.random.randn(n_inputs,n_hidden)
W2 = np.random.randn(n_hidden,n_hidden)
W3 = np.random.randn(n_hidden,n_output)


b1 = np.random.randn(n_hidden)
b2 = np.random.randn(n_hidden)

In [9]:
x = np.random.randn(n_inputs)

In [11]:
for n in range(1001):
    z1 = x @ W1 + b1
    a1 = sigmoid(z1)
    
    z2 = a1 @ W2
    a2 = sigmoid(z2)
    
    z3 = a1 @ W3
        
#     a3 = f(z3)   ## Apply activation function to output layer?
    a3 = z3
    y = a3

    if n%100 == 0:
        print(MSE(y,target))

    l3 = MSE(y, target, True)
    l2 = (W3 @ l3) * sigmoid(z2, True)
    l1 = (W2 @ l2) * sigmoid(z1, True)
    
#     print(l3.shape)

    W1 = W1 - lr*(
        np.repeat(x[:,None], l1.shape[0], axis=1) *
        np.repeat(l1[None,:], x.shape[0], axis=0)
    )
#     print(l1.shape)
#     print(np.repeat(x[:,None], l1.shape[0], axis=1).shape)
#     print(np.repeat(l1[None,:], x.shape[0], axis=0).shape)
    W2 = W2 - lr*(
        np.repeat(a1[:,None], l2.shape[0], axis=1) *
        np.repeat(l2[None,:], a1.shape[0], axis=0)
    )
    W3 = W3 - lr*(
        np.repeat(a2[:,None], l3.shape[0], axis=1) *
        np.repeat(l3[None,:], a2.shape[0], axis=0)
    )
    
    b1 = b1 - l1
    b2 = b2 - l2

3.91691208298146e-20
1.5725739916030807e-22
8.794953067289786e-25
6.565601458045244e-27
3.879824054529234e-28
1.7936598202568913e-28
1.0090821832321966e-28
8.719991120225798e-29
8.305037958127901e-29
8.410794623234093e-29
8.550047061933068e-29


In [12]:
y, target

(array([-0.29769533, -0.21971084, -0.61309517, -0.05324452,  0.80514719,
        -0.96867515, -0.77814242, -0.19863168, -0.34148069,  0.04386213]),
 array([-0.29769533, -0.21971084, -0.61309517, -0.05324452,  0.80514719,
        -0.96867515, -0.77814242, -0.19863168, -0.34148069,  0.04386213]))

In [13]:
np.sum((target-y)**2)/len(y)

8.550047061933068e-29